version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean deploy -s settings.xml
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'